services:
  karakeep:
    image: ghcr.io/karakeep-app/karakeep:0.27.1
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    volumes:
      - data:/data
    ports:
      - ${PANEL_APP_PORT_HTTP}:3000
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      NEXTAUTH_URL: http://localhost:3000
      DATA_DIR: /data
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:124
    container_name: chrome-${CONTAINER_NAME}
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.15.2
    container_name: meili-${CONTAINER_NAME}
    restart: unless-stopped
    environment:
      MEILI_NO_ANALYTICS: 'true'
    volumes:
      - meilisearch:/meili_data
volumes:
  meilisearch: null
  data: null
