services:
  moontv:
    image: ghcr.io/moontechlab/lunatv:v4.3.0
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:3000
    environment:
      - PASSWORD=${PASSWORD}
    labels:
      createdBy: Apps
networks:
  1panel-network:
    external: true
