services:
  it-tools:
    image: sharevb/it-tools:2025.8.31-13b8f041
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:8080
    labels:  
      createdBy: "Apps"
networks:  
  1panel-network:  
    external: true
